dependencies:
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::python=3.10
  - conda-forge::astropy
  - conda-forge::scipy
  - conda-forge::json
  - pip:
      - matplotlib
      - graphviz
# python=3.10 is needed because numba doesn't work with python>=3.11 - should be fixed end of 2023 // 21 mar 2023
